workflows:
  babysteps_workflow:
    name: Babysteps_WF
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      node: latest
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Install Node Dependencies
        script: npm install
      - name: Build iOS
        script: react-native build-ios --no-signature
    artifacts:
      - build/**/*.app
    publishing:
      email:
        recipients:
          - techdevmd@gmail.com
